language: java
sudo: required
dist: trusty
jdk:
- oraclejdk8

addons:
  ssh_known_hosts:
    - vpro0052.proserver.punkt.de
    - 217.29.41.52
  hosts:
    - ppr.surreal.is
  chrome: stable
  apt:
    packages:
      - unzip

script:
- curl -OL http://artfiles.org/apache.org/tomcat/tomcat-8/v8.5.23/bin/apache-tomcat-8.5.23.zip
- sudo unzip -q apache-tomcat-8*.zip -d /opt
- sudo mv /opt/apache-tomcat-8.5.23 /opt/tomcat
- sudo mv deployment/server.xml /opt/tomcat/conf/server.xml
- sudo chmod +x /opt/tomcat/bin/*
- sudo rm -rf /opt/tomcat/webapps/*
- ./gradlew clean --console=plain
- ./gradlew updateChromedriver --console=plain
- ./gradlew assemble --console=plain
- sudo cp $TRAVIS_BUILD_DIR/build/libs/* /opt/tomcat/webapps
- sudo /opt/tomcat/bin/startup.sh
- ./gradlew test --console=plain

before_deploy:
- openssl aes-256-cbc -K $encrypted_a907d4bfebdd_key -iv $encrypted_a907d4bfebdd_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -az --recursive --delete-after --progress --force --delete $TRAVIS_BUILD_DIR/build/libs/* proserver@vpro0052.proserver.punkt.de:/var/tomcat/webapps
  on:
    branch: master

notifications:
  email: travisdeployment@surreal.is
