language: java
sudo: required
dist: trusty
jdk:
- oraclejdk8

services:
- mysql

addons:
  ssh_known_hosts:
  - vpro0052.proserver.punkt.de
  - 217.29.41.52
  hosts:
  - ppr.surreal.is
  chrome: stable
  apt:
    packages:
    - unzip
    - figlet
    - cowsay
    - fortune

before_script:
- echo 'Project Puerto Rico' | figlet -w 120
- sed -n '633,649p' LICENSE.md
- mysql -e 'CREATE DATABASE IF NOT EXISTS ppr;'
- mysql -u root --default-character-set=utf8 ppr < structure.sql
- mysql -u root --default-character-set=utf8 ppr < filler.sql
- sudo rm -f $TRAVIS_BUILD_DIR/src/main/resources/application.properties
- sudo mv $TRAVIS_BUILD_DIR/deployment/application.properties $TRAVIS_BUILD_DIR/src/main/resources/application.properties

script:
- curl -OL https://ftp-stud.hs-esslingen.de/Mirrors/ftp.apache.org/dist/tomcat/tomcat-8/v8.5.31/bin/apache-tomcat-8.5.31.zip
- sha1sum -c deployment/tomcat_sha1
- sudo unzip -q apache-tomcat-8*.zip -d /opt
- sudo mv /opt/apache-tomcat-8.5.31 /opt/tomcat
- sudo mv deployment/server.xml /opt/tomcat/conf/server.xml
- sudo chmod +x /opt/tomcat/bin/*
- sudo rm -rf /opt/tomcat/webapps/*
- "./gradlew clean --console=plain"
- "./gradlew updateChromedriver --console=plain"
- "./gradlew assemble --console=plain"
- sudo cp $TRAVIS_BUILD_DIR/build/libs/* /opt/tomcat/webapps
- sudo /opt/tomcat/bin/startup.sh
- "./gradlew test --console=plain"

before_deploy:
- openssl aes-256-cbc -K $encrypted_a907d4bfebdd_key -iv $encrypted_a907d4bfebdd_iv -in deployment/secrets/secrets.tar.enc -out deployment/secrets/secrets.tar -d
- tar xvf deployment/secrets/secrets.tar
- sudo rm -f $TRAVIS_BUILD_DIR/src/main/resources/application.properties
- sudo mv deployment/secrets/application.properties src/main/resources/application.properties
- "./gradlew assemble"
- sudo mv deployment/secrets/deploy_rsa /tmp/deploy_rsa
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -az --recursive --delete-after --progress --force --delete $TRAVIS_BUILD_DIR/build/libs/* proserver@vpro0052.proserver.punkt.de:/var/tomcat/webapps
  on:
    branch: master

after_success:
- /usr/games/fortune | /usr/games/cowsay

notifications:
  email: travisdeployment@surreal.is
