language: java
sudo: required
dist: trusty
jdk:
- oraclejdk8

services:
- mysql

addons:
  ssh_known_hosts:
  - vpro0052.proserver.punkt.de
  - 217.29.41.52
  hosts:
  - ppr.surreal.is
  chrome: stable
  apt:
    packages:
    - unzip
    - figlet
    - cowsay
    - fortune

before_script:
- echo 'Project Puerto Rico' | figlet -w 120
- sed -n '633,649p' LICENSE.md
- mysql -e 'CREATE DATABASE IF NOT EXISTS ppr;'
- mysql -u root --default-character-set=utf8 ppr < structure.sql
- mysql -u root --default-character-set=utf8 ppr < filler.sql
- sudo rm -f $TRAVIS_BUILD_DIR/src/main/resources/application.properties
- sudo mv $TRAVIS_BUILD_DIR/deployment/application.properties $TRAVIS_BUILD_DIR/src/main/resources/application.properties

script:
- "./gradlew npmSetup --console=plain"
- "./gradlew npmInstall --console=plain"
- "./gradlew nodeSetup --console=plain"
- "./gradlew npm_run_dev --console=plain &"
- sleep 20
- "./gradlew updateChromedriver --console=plain"
- "./gradlew bootRun --console=plain &"
- sleep 30
- "./gradlew test --console=plain"
- "./gradlew jacocoTestReport"
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- openssl aes-256-cbc -K $encrypted_a907d4bfebdd_key -iv $encrypted_a907d4bfebdd_iv -in deployment/secrets/secrets.tar.enc -out deployment/secrets/secrets.tar -d
- tar xvf deployment/secrets/secrets.tar
- sudo rm -f $TRAVIS_BUILD_DIR/src/main/resources/application.properties
- sudo mv deployment/secrets/application.properties src/main/resources/application.properties
- "./gradlew npm_run_build --console=plain"
- "./gradlew clean assemble --console=plain"
- sudo mv deployment/secrets/deploy_rsa /tmp/deploy_rsa
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -az --recursive --delete-after --progress --force --delete $TRAVIS_BUILD_DIR/build/libs/* proserver@vpro0052.proserver.punkt.de:/var/tomcat/webapps
  on:
    branch: master

after_success:
- /usr/games/fortune | /usr/games/cowsay

notifications:
  email: travisdeployment@surreal.is
